name: Publish Documentation

on:
  push:
    branches:
      - docs

jobs:
  docs:
    name: DOCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598 # https://github.com/actions/checkout/releases/tag/v2.0.0
      - name: Install dependencies
        run: |
          npm ci
      - name: Build docs
        run: |
          npm run docs:build
      - name: Publish docs
        uses: malept/github-action-gh-pages@1b5c02254dc36eacd86e4e29bd18b6b1b9aadc67 # https://github.com/malept/github-action-gh-pages/releases/tag/v1.0.2
        with:
          docsPath: docs/.vuepress/dist
          publishBranch: gh-pages
